"""Configuration module for Academic RAG System"""

from .settings import AppSettings, settings
from .constants import (
    COURSE_CODE_REGEX,
    COURSE_CODE_PATTERN,
    LECTURER_PATTERN,
    SECTION_KEYWORDS,
    CONFIDENCE_WEIGHTS,
    LECTURER_QUERY_KEYWORDS,
    COMPARISON_QUERY_KEYWORDS,
    DEFAULT_FUZZY_MATCH_CUTOFF,
    DEFAULT_TEMPERATURE,
    DEFAULT_TOP_K,
    DEFAULT_LECTURER_K,
    DEFAULT_RERANK_TOP_K,
    MAX_QUERY_LENGTH,
    MIN_QUERY_LENGTH,
    MAX_CONTEXT_DOCS,
    MAX_RERANK_CANDIDATES,
)

__all__ = [
    "AppSettings",
    "settings",
    "COURSE_CODE_REGEX",
    "COURSE_CODE_PATTERN",
    "LECTURER_PATTERN",
    "SECTION_KEYWORDS",
    "CONFIDENCE_WEIGHTS",
    "LECTURER_QUERY_KEYWORDS",
    "COMPARISON_QUERY_KEYWORDS",
    "DEFAULT_FUZZY_MATCH_CUTOFF",
    "DEFAULT_TEMPERATURE",
    "DEFAULT_TOP_K",
    "DEFAULT_LECTURER_K",
    "DEFAULT_RERANK_TOP_K",
    "MAX_QUERY_LENGTH",
    "MIN_QUERY_LENGTH",
    "MAX_CONTEXT_DOCS",
    "MAX_RERANK_CANDIDATES",
]
